# NAME: Kanisha Shah
# EMAIL: kanishapshah@gmail.com
# ID: 504958165

default:
	gcc -g -Wall -Wextra -o lab1a lab1a.c

clean:
	rm -rf lab1a *.tar.gz *.dSYM

dist:
	tar -cvzf lab1a-504958165.tar.gz lab1a.c Makefile README 
