# NAME: Kanisha Shah, Nina Maller
# EMAIL: kanishapshah@gmail.com, nina.maller@gmail.com
# ID: 504958165, 604955977

default:
	rm -f lab3b
	ln lab3b_script lab3b
	chmod u+x lab3b

clean:
	rm -rf lab3b *.tar.gz *.dSYM

dist:
	tar -cvzf lab3b-504958165.tar.gz lab3b.py lab3b_script Makefile README
