# NAME: Kanisha Shah, Nina Maller
# EMAIL: kanishapshah@gmail.com, nina.maller@gmail.com
# ID: 504958165, 604955977

default:
	gcc -g -Wall -Wextra -o lab3a lab3a.c

clean:
	rm -rf lab3a *.tar.gz *.dSYM

dist:
	tar -cvzf lab3a-504958165.tar.gz lab3a.c Makefile README ext2_fs.h
