# NAME: Kanisha Shah
# EMAIL: kanishapshah@gmail.com
# ID: 504958165

default:
	gcc -g -Wall -Wextra -o lab0 lab0.c

check:
	./labcheck.sh

clean:
	rm -rf lab0 *.tar.gz *.dSYM

dist:
	tar -cvzf lab0-504958165.tar.gz lab0.c backtrace.png breakpoint.png Makefile README labcheck.sh
